#!/bin/sh
dirs=$*
if [[ $# -lt 1 ]]; then
  dirs='*'
fi
for dir in $dirs; do
  if [ -d $dir ]; then
    cd "$dir"
    if [ -d .git ]; then
      echo "=> $(color blue)$dir$(color off)"
      git branch
    fi
    cd $OLDPWD
  fi
done
