#!/bin/sh
proj_dir=~/src
brew update
brew upgrade
brew cleanup -s --force
npm update -g
for x in $(cat ~/Documents/install/gems.txt ); do gem update $x; done
update-repos $proj_dir/*
cd $proj_dir/dotfiles && git submodule foreach git pull
