#!/bin/sh

if [[ $# -lt 1 ]]; then
  echo "Usage: $0 database"
  exit
fi

db=$1

vacuumdb $1

psql -t $db <<-SQL
  SELECT 
    nspname AS schemaname, relname, reltuples
  FROM pg_class C
  LEFT JOIN pg_namespace N ON (N.oid = C.relnamespace)
  WHERE 
    nspname NOT IN ('pg_catalog', 'information_schema') AND
    relkind='r' 
  ORDER BY reltuples DESC;

  SELECT pg_size_pretty(pg_database_size('$db'));
SQL
