#!/usr/bin/env zsh
d() {
  git push origin :$1
}

for b in $(git branch -r --merged develop | sed 's/ *origin\///' | egrep -v '(master|develop)$'); do
  doit=
  vared -p "Delete $b? y or any other key to skip: " doit
  [[ $doit == "y" ]] && d $b
done
