#!/bin/sh
root='/Users/mdi/projects'
projects=$(cat ~/.projects)
for project in $projects; do
  cd "$root/$project"
  if [ -f "Gemfile" ]; then
    echo "=> $(color blue)$project$(color off)"
    bundle $@
  else
    break
  fi
done
