#!/bin/sh
printf "%-20s %8s %s\n" 'Process' 'PID' 'Port'
echo "==============================================================================="
lsof -i -P|grep -i listen|sort|awk '{printf "%-20s %8s %s\n", $1, $2, $9}'
