#!/bin/sh
for i in $(/bin/ls -Rl@ "$1" | grep "\t" | awk '{print $1}' | sort -u); do \
  echo Removing $i ... >&2; \
  if [ -d "$1" ]; then
    find . -print0 | xargs -0 xattr -d $i 2>/dev/null
  else
    xattr -d $i "$1"
  fi
done
