#!/bin/bash
dirs=$*
if [ -z "$1" ]; then
  dirs='*'
fi

for dir in $dirs; do
  if [ -d $dir ]; then
    cd "$dir"

    if [ -d .git ] || [ -d .svn ] || [ -d .hg ]; then
      echo "=> $(color blue)$dir$(color off)"

      if [ -d .git ]; then
        git pull
      elif [ -d .svn ]; then
        svn up
      elif [ -d .hg ]; then
        hg update
      fi
    fi

    cd $OLDPWD
  fi
done
